Backend/gestion/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import UserDataView
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from iva import views
from tesoreria.views import NotificacionesList

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api', include(router.urls)),
    path('api/user/', UserDataView.as_view(), name="user_data"),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/iva/', include('iva.urls')),
    path('api/tesoreria/', include('tesoreria.urls')),
    path('api/reportes/', include('reportes.urls')),
    path('api/inversiones/', include('inversiones.urls')),
    path('api/notificaciones/', NotificacionesList.as_view(), name="notificaciones"),
    path('api/shared/', include('shared.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/iva/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = "iva"
urlpatterns = [
    path("", views.DocumentoList.as_view(), name="index"),
    path("clientes_proyectos/", views.ClienteProyectoList.as_view(), name="clientes_proyectos"),
    path("clientes_proyectos/<int:pk>/",views.ClienteProyectoDetail.as_view(),name="cliente_proyecto_detail"),
    path("tipos_documento/", views.TipoDocumentoList.as_view(), name="tipos_documento"),
    path("activos/", views.DocumentoActivoViewSet.as_view(), name="documentos_activos"),
    path("impagos/", views.DocumentoImpagoViewSet.as_view(), name="documentos_impagos"),
    path("inactivos/", views.DocumentoInactivoViewSet.as_view(), name="documentos_inactivos"),
    path("imputaciones/", views.ImputacionList.as_view(), name="imputacion"),
    path("proveedores/", views.ProveedorList.as_view(), name="proveedor"),
    path("personas/<int:pk>/",views.PersonaDetail.as_view(),name="persona_detail"),
    path("receptores/",views.ReceptorList.as_view(),name="receptores"),
    path("unidades_de_negocio/",views.UnidadDeNegocioList.as_view(), name="unidades_de_negocio"),
    path('<int:pk>/', views.DocumentoDetail.as_view(), name="documento_detail"),
    path('<int:pk>/historial/',views.HistorialDocumento.as_view(), name="historial"),
    path('token/', views.CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', views.CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/restaurar/', views.RestaurarDocumento.as_view(), name='restaurar_documento'),
    path('exportar/', views.ExportarDocumentos.as_view(), name='exportar_archivos'),
    path('pagar_documento/', views.InformarPagoDocumento.as_view(), name='pagar_documento'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

Backend/iva/models.py
from ast import mod
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import transaction
from tesoreria.models import Caja, Registro

class Persona(models.Model):
    proveedor_receptor_choices = [
        (1, "Proveedor"),
        (2, "Receptor")
    ]
    razon_social = models.CharField(max_length=100, null=True, blank=True)
    nombre_fantasia = models.CharField(max_length=100, null=True, blank=True)
    proveedor_receptor = models.IntegerField(choices=proveedor_receptor_choices, default=1)
    cnpj = models.CharField(max_length=18, null=True, blank=True)
    cbu_alias = models.CharField(max_length=35, null=True, blank=True)
    #empleado = models.BooleanField(default=False)
    imputacion = models.ForeignKey('iva.imputacion', on_delete=models.DO_NOTHING, null=True, blank=True)
    activo = models.BooleanField(default=True)

    def __str__(self):
        if self.razon_social and self.nombre_fantasia:
            return f"{self.razon_social} ({self.nombre_fantasia})"
        return self.razon_social or self.nombre_fantasia or "Sin nombre"

    def delete(self, *args, **kwargs):
        self.activo = False
        self.save()
    
    def nombre(self):
        return self.razon_social or self.nombre_fantasia or "Sin nombre"

    class Meta:
        verbose_name = "Persona"
        verbose_name_plural = "Personas"
        ordering = ['nombre_fantasia']

class TiposDocumento(models.Model):
    tipo_documento = models.CharField(max_length=30)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.tipo_documento

class UnidadDeNegocio(models.Model):
    unidad_de_negocio = models.CharField(max_length=30)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.unidad_de_negocio

class ClienteProyecto(models.Model):
    cliente_proyecto = models.CharField(max_length=50)
    activo = models.BooleanField(default=True)
    unidad_de_negocio = models.ForeignKey(UnidadDeNegocio, on_delete=models.DO_NOTHING, default=1)
    porcentaje = models.DecimalField(decimal_places=2, max_digits= 5, default=100.00)

    def __str__(self):
        return self.cliente_proyecto
    
    def delete(self, *args, **kwargs):
        self.activo = False
        self.save()

class Imputacion(models.Model):
    imputacion = models.CharField(max_length=100)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.imputacion

class Documento(models.Model):

    def ruta_archivo(instance, filename):
        # Obtener el nombre del proveedor
        proveedor_nombre = instance.proveedor.razon_social.replace(" ", "_")
        # Obtener el año actual o de la fecha de la factura
        año = instance.fecha_documento.year
        # Crear la ruta completa
        ruta = f"documentos/{proveedor_nombre}/{año}/{filename}"  
        return ruta

    tipo_documento = models.ForeignKey(TiposDocumento, on_delete=models.DO_NOTHING, blank=False,null=False)
    fecha_documento = models.DateField()
    proveedor = models.ForeignKey(Persona, on_delete=models.DO_NOTHING, related_name="proveedor_documento")
    receptor = models.ForeignKey(Persona, on_delete=models.DO_NOTHING, related_name="receptor_documento")
    serie = models.SmallIntegerField(default=0)
    numero = models.IntegerField()
    chave_de_acesso = models.BigIntegerField
    añomes_imputacion_gasto = models.IntegerField()
    añomes_imputacion_contable = models.IntegerField(
    validators=[
        MinValueValidator(202001),  # Enero 2020
        MaxValueValidator(209912)   # Diciembre 2099
    ], default=202509)
    tiene_cno = models.BooleanField(default=False)
    unidad_de_negocio = models.ForeignKey(UnidadDeNegocio, on_delete=models.DO_NOTHING, null=True)
    cliente_proyecto = models.ForeignKey(ClienteProyecto, on_delete=models.DO_NOTHING, null=True)
    imputacion = models.ForeignKey(Imputacion, on_delete=models.DO_NOTHING, null=True)
    concepto = models.CharField(max_length=100)
    comentario = models.CharField(max_length=100, null=True, blank=True)
    total = models.DecimalField(decimal_places=2, max_digits= 15, null=True, blank=True)
    impuestos_retidos = models.DecimalField(decimal_places=2, max_digits= 15, null=True, blank=True)
    moneda = models.ForeignKey('shared.Moneda', on_delete=models.DO_NOTHING)
    fecha_pago = models.DateField(null=True, blank=True)
    archivo = models.FileField(upload_to=ruta_archivo)
    fecha_carga = models.DateTimeField(auto_now_add=True)
    municipio = models.ForeignKey('shared.Municipio', on_delete=models.DO_NOTHING, null=True)
    imputado = models.BooleanField(default=False) # Indica si el documento tiene un registro FC asociado
    activo = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.proveedor} - {self.tipo_documento} {self.serie}-{self.numero}"
    
    def delete(self, user=None, *args, **kwargs):
        # Marcar como eliminado en lugar de borrar realmente
        self.activo = False
        self.save()

    @transaction.atomic
    def imputar(self, fecha_reg, monto_pagado=None):
        self.imputado = True
        self.save(update_fields=['imputado'])
        registro = Registro.objects.create(
            tipo_reg = 'FC',
            fecha_reg = fecha_reg,
            añomes_imputacion = self.añomes_imputacion_gasto,
            unidad_de_negocio = self.unidad_de_negocio,
            cliente_proyecto = self.cliente_proyecto,
            proveedor = self.proveedor,
            imputacion = self.imputacion,
            observacion = self.concepto,
            monto_gasto_ingreso_neto = -monto_pagado if monto_pagado else -self.total,
            moneda = self.moneda,
            caja = Caja.objects.get_or_create(caja='Facturas')[0]
        )
        registro.documento.set([self])
        return registro

    
    class Meta:
        unique_together = ('tipo_documento', 'serie', 'numero', 'proveedor', 'activo')
    ordering = ['-fecha_documento', '-id']
    
    def validate_unique(self, exclude=None):
        super().validate_unique(exclude)
        if Documento.objects.filter(
            tipo_documento=self.tipo_documento,
            serie=self.serie,
            numero=self.numero,
            proveedor=self.proveedor,
            activo=self.activo
        ).exclude(pk=self.pk).exists():
            raise ValidationError(
                {'__all__': 'Ya existe un documento activo con ese tipo, Serie, número y proveedor.'}
            )

class EstadoDocumento(models.Model):

    ESTADOS_CHOICES = [
        (1,"Cargado"),
        (2, "Modificado"),
        (3,"Pagado"),
        (4,"Eliminado"),
        (5,"Restaurado")
    ]

    documento = models.ForeignKey(Documento,on_delete=models.DO_NOTHING)
    estado = models.IntegerField(choices=ESTADOS_CHOICES, default=1)
    usuario = models.ForeignKey(User, null=True, blank=True,related_name='documentos_eliminados', on_delete=models.DO_NOTHING)
    timestamp = models.DateTimeField(auto_now_add=True)

Backend/iva/forms.py
from django import forms
from .models import Documento

class DocumentoForm(forms.ModelForm):
    class Meta:
        model = Documento
        fields = ['tipo_documento','fecha_documento','proveedor','receptor','serie','numero', 'añomes_imputacion_gasto',
                  'unidad_de_negocio', 'cliente_proyecto', 'imputacion', 'concepto', 'comentario', 'neto', 'iva', 'percepcion_de_iva',
                  'percepcion_de_iibb','no_gravado','exento','moneda','tipo_de_cambio','archivo']

Backend/iva/templates/iva/actualizar.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión Quinto Diseño - Actualizar documento</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'iva/iconos/icono.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<div style="font-family: Arial, sans-serif; max-width: 1920px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333; border-bottom: 2px solid #333; padding-bottom: 10px;">Actualizar documento</h1>
    <div style="display: flex; flex-wrap: wrap; justify-content: space-between; margin-top: 20px;">
        <div style="flex: 1; min-width: 300px; max-width: 400px;background-color: #f9f9f9; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
            <form method="post"enctype="multipart/form-data">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Guardar cambios</button>
                </form>
        </div>
        <div style="flex: 1; min-width: 300px; min-height: 820;max-width: 1400px; margin-top: 20px; margin-right: 20px; margin-left: 20px;text-align: center;">
            {% if documento.archivo %}
            <object
            data="{{ documento.archivo.url }}"
            type="application/pdf"
            width="100%"
            height="100%"
        >
            <p>Este documento o tu dispositivo no permite la vista previa. Podés <a href="{{ documento.archivo.url }}" target="_blank" rel="noopener noreferrer">abrirlo en una pestaña nueva</a>.</p>
            </object>
            {% else %}
            <p style="color: #666; font-style: italic; background-color: #f9f9f9; padding: 20px; border-radius: 8px;">No hay imagen disponible para esta factura.</p>
            {% endif %}
        </div>
    </div>
</div>

Backend/iva/templates/iva/carga.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión Quinto Diseño - Cargar documento</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'iva/iconos/icono.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333; border-bottom: 2px solid #333; padding-bottom: 10px;">Cargar documento</h1>
    <div style="flex: 1; min-width: 300px; background-color: #f9f9f9; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
        <form method="post"enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Cargar</button>
        </form>
    </div>
</div>

Backend/iva/templates/iva/detalle.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión Quinto Diseño - Detalle documento</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'iva/iconos/icono.ico' %}">
</head>
<div style="font-family: Arial, sans-serif; max-width: 1920px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333; border-bottom: 2px solid #333; padding-bottom: 10px;">Detalle del documento</h1>
    
    <div style="display: flex; flex-wrap: wrap; justify-content: space-between; margin-top: 20px;">
        <div style="flex: 1; min-width: 300px; max-width: 400px;background-color: #f9f9f9; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
            <h2 style="color: #444; margin-bottom: 15px;">Información de la Factura</h2>
            <p><strong style="color: #666;">Proveedor:</strong> <span style="color: #333;">{{ documento.proveedor }}</span></p>
            <p><strong style="color: #666;">Fecha:</strong> <span style="color: #333;">{{ documento.fecha_documento }}</span></p>
            <p><strong style="color: #666;">Tipo:</strong> <span style="color: #333;">{{ documento.tipo_documento.tipo_documento }}</span></p>
            <p><strong style="color: #666;">Serie:</strong> <span style="color: #333;">{{ documento.serie }}</span></p>
            <p><strong style="color: #666;">Número:</strong> <span style="color: #333;">{{ documento.numero }}</span></p>
        </div>
        
        <div style="flex: 1; min-width: 300px; min-height: 820;max-width: 1400px; margin-top: 20px; margin-right: 20px; margin-left: 20px;text-align: center;">
            {% if documento.archivo %}
            <object
            data="{{ documento.archivo.url }}"
            type="application/pdf"
            width="100%"
            height="100%"
        >
            <p>Este documento o tu dispositivo no permite la vista previa. Podés <a href="{{ documento.archivo.url }}" target="_blank" rel="noopener noreferrer">abrirlo en una pestaña nueva</a>.</p>
            </object>
            {% else %}
            <p style="color: #666; font-style: italic; background-color: #f9f9f9; padding: 20px; border-radius: 8px;">No hay imagen disponible para esta factura.</p>
            {% endif %}
        </div>
    </div>
</div>

Backend/iva/templates/iva/eliminar.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión Quinto Diseño - Eliminar documento</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'iva/iconos/icono.ico' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333; border-bottom: 2px solid #333; padding-bottom: 10px;">Eliminar documento</h1>
    <div style="flex: 1; min-width: 300px; background-color: #f9f9f9; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
        <form method="post">
            {% csrf_token %}
            <p>¿Está seguro de que quiere eliminar "{{ object }}"?</p>
            <button type="submit">Sí</button>
            <a href="{% url 'iva:index' %}"><button type="button">No</button></a>
        </form>
    </div>
</div>

Backend/iva/templates/iva/historial.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión Quinto Diseño - Historial documento</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'iva/iconos/icono.ico' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f4f4f4;
        }
        h1 {
            color: #2c3e50;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            background-color: white;
            box-shadow: 0 1px 3px rgba(0,0,0,0.2);
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #2c3e50;
            color: white;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #ddd;
        }
        @media screen and (max-width: 600px) {
            table, thead, tbody, th, td, tr {
                display: block;
            }
            thead tr {
                position: absolute;
                top: -9999px;
                left: -9999px;
            }
            tr {
                border: 1px solid #ccc;
                margin-bottom: 10px;
            }
            td {
                border: none;
                position: relative;
                padding-left: 50%;
            }
            td:before {
                position: absolute;
                top: 6px;
                left: 6px;
                width: 45%;
                padding-right: 10px;
                white-space: nowrap;
                content: attr(data-label);
                font-weight: bold;
            }
        }
    </style>
</head>
{% load gestion_extras %}
{% if request.user|has_group:"Administracion" %}
<body>
    <h1>Historial del documento - {{ estados.0.documento }}</h1>
    
    <table>
        <thead>
            <tr>
                <th>Estado</th>
                <th>Fecha</th>                      
                <th>Usuario</th>
            </tr>
        </thead>
        <tbody>
            {% for estado in estados %}
            <tr>
                <td data-label="Estado">{{ estado.get_estado_display }}</td>
                <td data-label="Fecha">{{ estado.timestamp }}</td>
                <td data-label="Usuario">{{ estado.usuario }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
{% endif %}
</html>

Backend/iva/templates/iva/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión Quinto Diseño - Documentos</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'iva/iconos/icono.ico' %}">
    <link rel="stylesheet" href="{% static 'iva/styles.css' %}">
</head>

<body>
    
    {% block content %}
    <div class="container">
        <main class="invoice-list">
            <header style="display: flex; justify-content: space-between; align-items: center;">
                <h1 style="margin: 0;">{{titulo}}</h1>
                <div style="display: flex; gap: 10px;">
                    {% load gestion_extras %}
                    {% if request.user|has_group:"Administracion" %}
                    {% if titulo == "Documentos Cargados" %}
                    <a href="{% url 'iva:eliminados' %}"><button id="toggleForm" class="toggle-form-btn">Documentos Eliminados</button></a>
                    {% else %}
                    <a href="{% url 'iva:index' %}"><button id="toggleForm" class="toggle-form-btn">Documentos Cargados</button></a>
                    {% endif %}
                    {% endif %}
                    <a href="{% url 'iva:carga' %}"><button id="toggleForm" class="toggle-form-btn">Cargar Nuevo Documento</button></a>
                </div>
            </header>
            <table>
                <thead>
                    <tr>
                        <th>Tipo</th>
                        <th>Fecha</th>
                        <th>Proveedor</th>                        
                        <th>Receptor</th>
                        <th>PV</th>
                        <th>Número</th>
                        <th>Comentario</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for documento in documentos %}
                    <tr>
                        <td>{{ documento.tipo_documento.tipo_documento }}</td>
                        <td>{{ documento.fecha_documento }}</td>
                        <td>{{ documento.proveedor.razon_social }}</td>
                        <td>{{ documento.receptor.razon_social }}</td>
                        <td>{{ documento.serie }}</td>
                        <td>{{ documento.numero }}</td>
                        <td>{{ documento.comentario }}</td>
                        <td>
                            <a href="{% url 'iva:detalle' documento.id %}"><img src="{% static 'iva/iconos/ver.png' %}" alt="Ver" style="width:16px; height:16px;"></a>
                            {% if titulo == "Documentos Cargados" %}
                            <a href="{% url 'iva:actualizar' documento.id %}"><img src="{% static 'iva/iconos/actualizar.png' %}" alt="Actualizar" style="width:16px; height:16px;"></a>
                            {% if request.user|has_group:"Administracion" %}
                            <a href="{% url 'iva:eliminar' documento.id %}"><img src="{% static 'iva/iconos/1345874.png' %}" alt="Eliminar" style="width:16px; height:16px;"></a>
                            {% endif %}
                            {% endif %}
                            {% if request.user|has_group:"Administracion" %}
                            <a href="{% url 'iva:historial' documento.id %}"><img src="{% static 'iva/iconos/historial.png' %}" alt="Historial" style="width:16px; height:16px;"></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </main>
    </div>
    {% endblock %}
</body>
<a href="{% url 'inicio' %}">
    <img src="{% static 'gestion/iconos/jt.png' %}" alt="Inicio" style="position: fixed; bottom: 10px; left: 10px; width: 50px; height: 50px; z-index: 1000;">
</a>
</html>